title: CAR 3i Network
short_title: 3i Network
description: CAR 3i Networks adalah suatu sistem pemasaran asuransi jiwa melalui jaringan keagenan, dimana 3i-Networks bertujuan untuk mengajak pemegang polis untuk memiliki perlindungan (proteksi), Investasi (Unit Link) dan juga penghasilan sebagai Agen Asuransi Jiwa (mengikuti peraturan keagenan yang berlaku).
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
